sudo: false

# For running jekyll
language: ruby

# Needed for some github-pages dependencies
rvm: 2.3

branches:
  only:
    - master
    - gh-pages

before_install:
  - gem install github-pages
  - pip install --user --upgrade pyopenssl
  - pip install --user ndg-httpsclient pyasn1 "requests[security]>=2.4.0" "urllib3[secure]>=1.22"
  - pip install --user git+https://github.com/linkcheck/linkchecker

script:
  - jekyll build 2>build.log
  - if [ -s build.log ]; then
        echo Build produced errors:;
        cat build.log;
        false;
    else
      echo Checking links;
      linkchecker --anchors --check-extern _site;
    fi
